# Generated by Django 4.2.10 on 2025-03-25 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255)),
                ('data_pesquisa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FonteAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('autores', models.CharField(blank=True, max_length=500, null=True)),
                ('instituicao', models.CharField(blank=True, max_length=255, null=True)),
                ('ano_publicacao', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes', to='search_engine.pesquisaacademica')),
            ],
        ),
    ]
