# Generated by Django 4.2.10 on 2025-03-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonteacademica',
            name='tipo_acesso',
            field=models.CharField(blank=True, help_text='Tipo de acesso ao documento, ex: PDF, Texto completo, Acesso aberto', max_length=100, null=True),
        ),
    ]
